micronaut:
  server:
    port: 8080

datasources:
  default:
    url: jdbc:postgresql://localhost/conference-db
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver