micronaut:
  ssl:
    port: 8080
    enabled: true
    buildSelfSigned: true

datasources:
  default:
    url: jdbc:postgresql://localhost/conference-db
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver