micronaut:
  server:
    port: 8070

datasources:
  default:
    url: jdbc:postgresql://localhost/author-db
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver